export default {
    processesList: [
        {
          owner: 'PLAY',
          id: 'PLAYCreate or Update Trade',
          name: 'Create or Update Trade',
          dataType: 'InterfaceMessage',
          description: null,
          processorClassName: 'com.cyoda.processors.CreateNextLifecycleMessage',
          parameters: [],
          fields: [],
          syncProcess: false,
          newTransactionForAsync: true,
          noneTransactionalForAsync: false,
        },
        {
          owner: 'PLAY',
          id: 'PLAYCreate Next Lifecycle Message',
          name: 'Create Next Lifecycle Message',
          dataType: 'InterfaceMessage',
          description: null,
          processorClassName: 'com.cyoda.processors.CreateNextLifecycleMessage',
          parameters: [],
          fields: [],
          syncProcess: false,
          newTransactionForAsync: true,
          noneTransactionalForAsync: false,
        },
        {
          owner: 'PLAY',
          id: 'PLAYGenerateMessageBodyFromPayload',
          name: 'GenerateMessageBodyFromPayload',
          dataType: 'InterfaceMessage',
          description: null,
          processorClassName: 'com.cyoda.processors.GenerateMessageBodyFromPayload',
          parameters: [],
          fields: [],
          syncProcess: false,
          newTransactionForAsync: false,
          noneTransactionalForAsync: false,
        },
        {
          owner: 'PLAY',
          id: 'PLAYGenerate Test Trade',
          name: 'Create Test Message From Seed',
          dataType: 'InterfaceMessage',
          description: null,
          processorClassName: 'com.cyoda.processors.CreateTestMessageFromSeedReactive',
          parameters: [
            {
              owner: 'PLAY',
              id: 'Create Test Message From Seed_param_url',
              name: 'url',
              dataType: null,
              description: null,
              valueType: 'java.lang.String',
              value: 'local',
              inputType: null,
            },
            {
              owner: 'PLAY',
              id: 'Create Test Message From Seed_param_credentials',
              name: 'credentials',
              dataType: null,
              description: null,
              valueType: 'java.lang.String',
              value: 'put perpetual access token here',
              inputType: null,
            },
          ],
          fields: [],
          syncProcess: false,
          newTransactionForAsync: true,
          noneTransactionalForAsync: false,
        },
      ],
    criteriaList: [
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisToDtccGtr',
          name: 'isToDtccGtr',
          dataType: 'InterfaceMessage',
          description: 'An FpML Message from a front office system',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.GroupCondition",\n "operator": "AND",\n "conditions": [{\n  "@bean": "com.cyoda.core.conditions.queryable.Equals",\n  "fieldName": "type",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "FpML"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "direction",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "OUT"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "gateway",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "DTCC"\n  },\n  "queryable": true\n }]\n}\n',
        },
        {
          owner: 'PLAY',
          id: '98aec400-f217-11e8-af8f-f6619b6570cb',
          name: '[ DUPLICATE ] isToDtccGtr',
          dataType: 'InterfaceMessage',
          description: 'An FpML Message from a front office system',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.GroupCondition",\n "operator": "AND",\n "conditions": [{\n  "@bean": "com.cyoda.core.conditions.queryable.Equals",\n  "fieldName": "type",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "FpML"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "direction",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "OUT"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "gateway",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "DTCC"\n  },\n  "queryable": true\n }]\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisFromFrontOffice',
          name: 'isFromFrontOffice',
          dataType: 'InterfaceMessage',
          description: 'An FpML Message from a front office system',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.GroupCondition",\n "operator": "AND",\n "conditions": [{\n  "@bean": "com.cyoda.core.conditions.queryable.Equals",\n  "fieldName": "type",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "FpML"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "direction",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "IN"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "gateway",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "FRONT_OFFICE"\n  },\n  "queryable": true\n }]\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisSeedProcessingNotDone',
          name: 'isSeedProcessingNotDone',
          dataType: 'InterfaceMessage',
          description: 'Does the seed message have to continue its job?',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.ConfigurableUnaryCondition",\n "invert": true,\n "unaryCondition": "com.cyoda.conditions.IsSeedProcessingDone"\n}',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisValidFpML',
          name: 'isValidFpML',
          dataType: 'InterfaceMessage',
          description: null,
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.ConfigurableUnaryCondition",\n "invert": false,\n "unaryCondition": "com.cyoda.conditions.IsValidFpML"\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisMatchedFpML',
          name: 'isMatchedFpML',
          dataType: 'InterfaceMessage',
          description: 'If this is an amendment message, is the corresponding trade existing and does it have the right state?',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.ConfigurableUnaryCondition",\n "invert": false,\n "unaryCondition": "com.cyoda.conditions.IsMatchedFpML"\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisFixMessage',
          name: 'isFixMessage',
          dataType: 'InterfaceMessage',
          description: 'A FIXML message',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.GroupCondition",\n "operator": "AND",\n "conditions": [{\n  "@bean": "com.cyoda.core.conditions.queryable.Equals",\n  "fieldName": "type",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "FIXML"\n  },\n  "queryable": true\n }, {\n  "@bean": "Equals",\n  "fieldName": "direction",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "IN"\n  },\n  "queryable": true\n }]\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisForTestDataGeneration',
          name: 'isForTestDataGeneration',
          dataType: 'InterfaceMessage',
          description: 'A message to generate test data (FpML messages)',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.GroupCondition",\n "operator": "AND",\n "conditions": [{\n  "@bean": "com.cyoda.core.conditions.queryable.Equals",\n  "fieldName": "type",\n  "operation": "EQUALS",\n  "value": {\n   "@type": "String",\n   "value": "SEED"\n  },\n  "queryable": true\n }]\n}\n',
        },
        {
          owner: 'PLAY',
          id: 'PLAYInterfaceMessageisSeedProcessingDone',
          name: 'isSeedProcessingDone',
          dataType: 'InterfaceMessage',
          description: 'Has the SEED message created the requisite number of test messages?',
          entityClassName: 'com.cyoda.core.model.message.InterfaceMessage',
          criteria: '{\n "@bean": "com.cyoda.core.conditions.ConfigurableUnaryCondition",\n "invert": false,\n "unaryCondition": "com.cyoda.conditions.IsSeedProcessingDone"\n}',
        },
      ],
    transitionsList: [
        {
          owner: 'PLAY',
          id: '4406204a-f214-11e8-af8f-f6619b6570cb',
          name: 'ttt',
          dataType: null,
          description: '',
          startStateId: 'noneState',
          startStateName: 'None',
          endStateId: '44f1439a-f214-11e8-af8f-f6619b6570cb',
          endStateName: 't',
          workflowId: 'acd34ef0-f213-11e8-af8f-f6619b6570cb',
          criteriaIds: [
            'PLAYInterfaceMessageisSeedProcessingNotDone',
          ],
          endProcessesIds: [
            'PLAYCreate or Update Trade',
          ],
          codeRule: null,
          active: true,
          automated: false,
          issueType: null,
          issueText: null,
          logActivity: false,
        },
        {
          owner: 'PLAY',
          id: '572aca9a-f214-11e8-af8f-f6619b6570cb',
          name: 'ttt',
          dataType: null,
          description: '',
          startStateId: 'noneState',
          startStateName: 'None',
          endStateId: '57c70a90-f214-11e8-af8f-f6619b6570cb',
          endStateName: 'ttt',
          workflowId: 'acd34ef0-f213-11e8-af8f-f6619b6570cb',
          criteriaIds: [
            'PLAYInterfaceMessageisToDtccGtr',
          ],
          endProcessesIds: [
            'PLAYCreate or Update Trade',
          ],
          codeRule: null,
          active: false,
          automated: false,
          issueType: null,
          issueText: null,
          logActivity: false,
        },
      ],
      workflowId: 'workflow-id',
    };
