#!/bin/bash

# Cyoda Backend Connection Setup Script
# This script helps you configure the backend connection for all React packages

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Default values
DEFAULT_BACKEND_URL="http://localhost:8080"
DEFAULT_API_BASE="${DEFAULT_BACKEND_URL}/api"
DEFAULT_PROCESSING_BASE="${DEFAULT_BACKEND_URL}/processing"

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}  Cyoda Backend Connection Setup${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# Function to create env file
create_env_file() {
    local package_path=$1
    local api_base=$2
    local processing_base=$3
    local env_file="${package_path}/.env.development.local"
    
    echo -e "${YELLOW}Creating ${env_file}...${NC}"
    
    cat > "${env_file}" << EOF
# API Configuration
VITE_APP_API_BASE=${api_base}
VITE_APP_API_BASE_PROCESSING=${processing_base}

# Debug
VITE_APP_DEBUG=true

# Auto-generated by setup-backend-connection.sh
# Generated on: $(date)
EOF
    
    echo -e "${GREEN}✓ Created ${env_file}${NC}"
}

# Function to update processing manager config
update_processing_config() {
    local backend_url=$1
    local config_file="packages/processing-manager-react/public/config.json"
    
    if [ -f "${config_file}" ]; then
        echo -e "${YELLOW}Updating ${config_file}...${NC}"
        
        cat > "${config_file}" << EOF
{
  "apiBaseUrl": "${backend_url}",
  "grafanaUrl": "http://localhost:3000",
  "enableSSH": true,
  "pollingInterval": 30000
}
EOF
        
        echo -e "${GREEN}✓ Updated ${config_file}${NC}"
    fi
}

# Check if mode is provided
MODE=${1:-"interactive"}

if [ "$MODE" = "local" ]; then
    echo -e "${GREEN}Setting up connection to LOCAL backend...${NC}"
    BACKEND_URL="${DEFAULT_BACKEND_URL}"
    API_BASE="${DEFAULT_API_BASE}"
    PROCESSING_BASE="${DEFAULT_PROCESSING_BASE}"
    
elif [ "$MODE" = "remote" ]; then
    echo -e "${GREEN}Setting up connection to REMOTE backend...${NC}"
    echo ""
    read -p "Enter backend URL (e.g., https://dev.cyoda.com): " BACKEND_URL
    
    if [ -z "$BACKEND_URL" ]; then
        echo -e "${RED}Error: Backend URL cannot be empty${NC}"
        exit 1
    fi
    
    API_BASE="${BACKEND_URL}/api"
    PROCESSING_BASE="${BACKEND_URL}/processing"
    
elif [ "$MODE" = "interactive" ]; then
    echo -e "${YELLOW}Interactive Setup${NC}"
    echo ""
    echo "Choose backend type:"
    echo "  1) Local backend (http://localhost:8080)"
    echo "  2) Remote backend (custom URL)"
    echo ""
    read -p "Enter choice [1-2]: " choice
    
    case $choice in
        1)
            BACKEND_URL="${DEFAULT_BACKEND_URL}"
            API_BASE="${DEFAULT_API_BASE}"
            PROCESSING_BASE="${DEFAULT_PROCESSING_BASE}"
            ;;
        2)
            read -p "Enter backend URL (e.g., https://dev.cyoda.com): " BACKEND_URL
            if [ -z "$BACKEND_URL" ]; then
                echo -e "${RED}Error: Backend URL cannot be empty${NC}"
                exit 1
            fi
            API_BASE="${BACKEND_URL}/api"
            PROCESSING_BASE="${BACKEND_URL}/processing"
            ;;
        *)
            echo -e "${RED}Invalid choice${NC}"
            exit 1
            ;;
    esac
else
    echo -e "${RED}Invalid mode: ${MODE}${NC}"
    echo "Usage: $0 [local|remote|interactive]"
    exit 1
fi

echo ""
echo -e "${BLUE}Configuration:${NC}"
echo -e "  Backend URL:     ${GREEN}${BACKEND_URL}${NC}"
echo -e "  API Base:        ${GREEN}${API_BASE}${NC}"
echo -e "  Processing Base: ${GREEN}${PROCESSING_BASE}${NC}"
echo ""

# Test backend connection
echo -e "${YELLOW}Testing backend connection...${NC}"
if curl -s -f -o /dev/null -m 5 "${BACKEND_URL}" 2>/dev/null || \
   curl -s -f -o /dev/null -m 5 "${API_BASE}" 2>/dev/null || \
   curl -s -o /dev/null -w "%{http_code}" -m 5 "${API_BASE}" 2>/dev/null | grep -q "401\|200"; then
    echo -e "${GREEN}✓ Backend is accessible${NC}"
else
    echo -e "${YELLOW}⚠ Warning: Could not connect to backend${NC}"
    echo -e "${YELLOW}  This is OK if the backend is not running yet${NC}"
fi

echo ""
read -p "Continue with setup? [Y/n]: " confirm
if [[ $confirm =~ ^[Nn]$ ]]; then
    echo "Setup cancelled"
    exit 0
fi

echo ""
echo -e "${BLUE}Creating environment files...${NC}"
echo ""

# List of packages to configure
PACKAGES=(
    "packages/cobi-react"
    "packages/tasks-react"
    "packages/processing-manager-react"
    "packages/source-configuration-react"
    "packages/statemachine-react"
    "packages/cyoda-sass-react"
)

# Special case for tableau (uses different base URL format)
TABLEAU_PACKAGE="packages/tableau-react"

# Create env files for all packages
for package in "${PACKAGES[@]}"; do
    if [ -d "$package" ]; then
        create_env_file "$package" "$API_BASE" "$PROCESSING_BASE"
    else
        echo -e "${YELLOW}⚠ Package not found: ${package}${NC}"
    fi
done

# Handle Tableau separately (uses full backend URL)
if [ -d "$TABLEAU_PACKAGE" ]; then
    create_env_file "$TABLEAU_PACKAGE" "$BACKEND_URL" "$PROCESSING_BASE"
fi

# Update processing manager config
update_processing_config "$BACKEND_URL"

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Setup Complete! ✓${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo ""
echo "1. Install dependencies (if not already done):"
echo -e "   ${YELLOW}npm install${NC}"
echo ""
echo "2. Start the development server:"
echo -e "   ${YELLOW}npm run dev${NC}"
echo ""
echo "3. Or start a specific package:"
echo -e "   ${YELLOW}cd packages/cobi-react && npm run dev${NC}"
echo ""
echo -e "${BLUE}Available Packages:${NC}"
echo "  • COBI (Main App):        http://localhost:3009"
echo "  • Tasks:                  http://localhost:3010"
echo "  • Processing Manager:     http://localhost:3008"
echo "  • Tableau Reports:        http://localhost:3007"
echo "  • Source Configuration:   http://localhost:5176"
echo "  • State Machine:          http://localhost:3014"
echo "  • SaaS Application:       http://localhost:3011"
echo ""
echo -e "${BLUE}Backend Connection:${NC}"
echo -e "  ${GREEN}${BACKEND_URL}${NC}"
echo ""
echo -e "For more information, see: ${YELLOW}BACKEND_CONNECTION_GUIDE.md${NC}"
echo ""

