export const j2ab = new Map<string, string>([
  ["java.util.UUID", "abColDefString"],
  ["java.lang.String", "abColDefString"],
  ["java.lang.Integer", "abColDefNumber"],
  ["int", "abColDefNumber"],
  ["java.lang.Short", "abColDefNumber"],
  ["short", "abColDefNumber"],
  ["java.lang.Long", "abColDefNumber"],
  ["long", "abColDefNumber"],
  ["java.lang.Byte", "abColDefNumber"],
  ["byte", "abColDefNumber"],
  ["java.lang.Character", "abColDefNumber"],
  ["char", "abColDefNumber"],
  ["java.math.BigDecimal", "abColDefNumber"],
  ["java.math.BigInteger", "abColDefNumber"],
  ["java.util.Date", "abColDefDate"],
  ["java.time.LocalDate", "abColDefDate"],
  ["org.joda.time.LocalDate", "abColDefDate"],
  ["java.time.LocalDateTime", "abColDefDate"],
  ["org.joda.time.LocalDateTime", "abColDefDate"],
  ["java.time.ZonedDateTime", "abColDefDate"],
  ["java.lang.Boolean", "abColDefBoolean"],
  ["boolean", "abColDefBoolean"],
]);
