import {library} from '@fortawesome/fontawesome-svg-core'
import {
  faAlignJustify,
  faBars,
  faBug,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCircleInfo,
  faCircleStop,
  faCircleExclamation,
  faCogs,
  faDownload,
  faHeading,
  faInfo,
  faInfoCircle,
  faKey,
  faLink,
  faList,
  faMagnifyingGlass,
  faPencilAlt,
  faPlus,
  faRepeat,
  faSearch,
  faSignOutAlt,
  faSyncAlt,
  faTasks,
  faTrash,
  faUpload,
  faUser,
  faFileArrowUp,
  faEyeSlash,
  faEye,
  faUpRightAndDownLeftFromCenter,
  faMinus,
  faChevronUp,
  faChevronDown,
} from "@fortawesome/free-solid-svg-icons";
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'

// @ts-ignore
library.add(
  faAlignJustify,
  faBars,
  faBug,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCircleInfo,
  faCircleStop,
  faCircleExclamation,
  faCogs,
  faDownload,
  faHeading,
  faInfo,
  faInfoCircle,
  faKey,
  faLink,
  faList,
  faMagnifyingGlass,
  faPencilAlt,
  faPlus,
  faRepeat,
  faSearch,
  faSignOutAlt,
  faSyncAlt,
  faTasks,
  faTrash,
  faUpload,
  faUser,
  faFileArrowUp,
  faEyeSlash,
  faEye,
  faUpRightAndDownLeftFromCenter,
  faMinus,
  faChevronUp,
  faChevronDown,
  faFileArrowUp,
);

export default {
  install: (app) => {
    app.component("font-awesome-icon", FontAwesomeIcon);
  }
}
